# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

#the name of the project
name: Node.js CI

#the automatic test trigger on pushes and pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#we define the actual jobs that will trigger on the above events
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        #test on these specific nodejs versions
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    #checks out the project, sets up the nodejs environment
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #install all dependencies based on package-lock.json
    - run: npm ci
    #runs test command based on package.json
    - run: npm test
